workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Получение зависимостей Flutter
        script: |
          flutter pub get
      - name: Установка CocoaPods
        script: |
          cd ios
          pod install
          cd ..
      - name: Сборка iOS приложения
        script: |
          flutter build ios --release --no-codesign
      - name: Создание IPA файла
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../../../PackardStopwatch.ipa Payload
    artifacts:
      - PackardStopwatch.ipa
