workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Очистка и подготовка
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Flutter.framework
          rm -rf ios/Flutter/Flutter.podspec
      - name: Получение зависимостей
        script: |
          flutter pub get
      - name: Установка CocoaPods
        script: |
          cd ios
          pod install
          cd ..
      - name: Сборка iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Создание IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../../../PackardStopwatch.ipa Payload
    artifacts:
      - PackardStopwatch.ipa
